/**  This file is automatically generated  **/

package main

////////////////////////////////////////////////////////////////

var GlobalDependenciesMap = map[string]string{
	"github.com/Bookshelf-Writer/SimpleGenerator": "v0.3.0",
	"github.com/fatih/color":                      "v1.18.0",
	"github.com/ghodss/yaml":                      "v1.0.0",
	"github.com/inconshreveable/mousetrap":        "v1.1.0",
	"github.com/mattn/go-colorable":               "v0.1.13",
	"github.com/mattn/go-isatty":                  "v0.0.20",
	"github.com/spf13/cobra":                      "v1.8.1",
	"github.com/spf13/pflag":                      "v1.0.5",
	"golang.org/x/crypto":                         "v0.31.0",
	"golang.org/x/sys":                            "v0.28.0",
	"gopkg.in/yaml.v2":                            "v2.4.0",
}
